#!/bin/bash
# generic documentation extractor for use with
# WORD delimited bash heredoc comment blocks
#
# a heredoc comment block begins with
:<<DOC
  and ends with
DOC
# where DOC is the heredoc WORD. It can be any single word.

[[ $# -lt 1 ]] && { echo >&2 "Usage: ${0} <scriptfile> [heredoc_WORD {default: DOC}]"; exit 1; }

declare script_file=${1}
[[ -f ${script_file} ]] || { echo >&2 "Error: ${script_file} not found"; exit 1; }

[[ ${2} ]] && {
    declare WORD=${2}
} || {
    declare WORD=DOC
}

declare found=
while IFS= read line; do
    [[ ${found} ]] || {
        [[ "${line}" =~ ^\:\<\<${WORD}$ ]] && found=true
    }
    case ${found} in
        true)
            [[ "${line}" =~ ^\:\<\<${WORD}$ ]] && continue
            [[ "${line}" =~ ^${WORD}$ ]] && { found=; continue; }
            printf '%s\n' "${line}"
            ;;
        *) continue ;;
    esac
done < <(cat ${script_file})

