#!/bin/bash
# generic README generator from DOC delimited comment heredoc
#
[[ $# -ne 1 ]] && { echo >&2 "${0} <scriptfile>"; exit 1; }

declare found=
>README
while IFS= read line; do
    [[ ${found} ]] || {
        [[ "${line}" =~ ^\:\<\<DOC$ ]] && found=true
    }
    case ${found} in
        true)
            [[ "${line}" =~ ^(\:\<\<DOC|DOC)$ ]] && continue
            printf '%s\n' "${line}" >> README
            ;;
        *) continue ;;
    esac
done < <(cat ${1})

